In [1]:
import os
import sys
import requests
import datetime as dt
from dotenv import load_dotenv
from pathlib import Path
import requests
import pandas as pd
import talib as ta
import plotly.graph_objs as go

import ipywidgets as widgets
from ipywidgets import Dropdown, Text, Button, Output
from IPython.display import display

from Modules.show_plot import ShowPlot
from Modules.reques_api import RequestApi
from Modules.get_market_data import GetMarketData

In [2]:
API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")
request_api = RequestApi(API_BASE_URL)
get_market_data = GetMarketData(Path('/workspace/data'))

#### 金価格の時系列データを取得

In [ ]:
gold = 'GC=F'
start = '1999-01-01'
end = '2026-04-25'
"""
response = request_api.update_commodity_timeseries_data(
    code='GC=F',
    market=None,
    start=start,
    end=end
)
response
"""

{'result': True}

In [4]:
gold_df = request_api.get_commodity_time_series_data(
    code=gold,
    market=None,
    start=start,
    end=end
)
gold_df.head()

取得件数: 6436

,id,commodity_id,commodity_code,commodity_market,date,open,high,low,close,adj_close,...,rci9,rci26,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,1,1,GC=F,None,2000-08-30,273.899994,273.899994,273.899994,273.899994,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,2,1,GC=F,None,2000-08-31,278.299988,278.299988,274.799988,274.799988,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,3,1,GC=F,None,2000-09-01,277.000000,277.000000,277.000000,277.000000,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,4,1,GC=F,None,2000-09-05,275.799988,275.799988,275.799988,275.799988,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,5,1,GC=F,None,2000-09-06,274.200012,274.200012,274.200012,274.200012,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False

#### 銀価格の時系列データを取得

In [ ]:
silver = 'SI=F'
"""
response = request_api.update_commodity_timeseries_data(
    code=silver,
    market=None,
    start=start,
    end=end
)
response
"""

{'result': True}

In [6]:
silver_df = request_api.get_commodity_time_series_data(
    code=silver,
    market=None,
    start=start,
    end=end
)
silver_df.head()

取得件数: 6438

,id,commodity_id,commodity_code,commodity_market,date,open,high,low,close,adj_close,...,rci9,rci26,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,6437,2,SI=F,None,2000-08-30,4.930,4.950,4.895,4.950,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,6438,2,SI=F,None,2000-08-31,5.003,5.045,4.920,4.920,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,6439,2,SI=F,None,2000-09-01,5.004,5.035,4.985,5.035,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,6440,2,SI=F,None,2000-09-05,4.998,5.005,4.975,4.990,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,6441,2,SI=F,None,2000-09-06,4.983,5.000,4.980,5.000,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False

#### VIX指数の時系列データを取得

In [ ]:
vix = '^VIX'
"""
response = request_api.update_stock_timeseries_data(
    code=vix,
    market=None,
    start=start,
    end=end
)
response
"""

{'result': True}

In [8]:
vix_timeseries_df = request_api.get_stock_time_series_data(
    code=vix,
    market=None,
    start=start,
    end=end
)
vix_timeseries_df.head()

取得件数: 6900

,id,stock_code,stock_market,date,open,high,low,close,volume,ma5,...,upper1,lower1,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,1062818,^VIX,None,1998-11-17,27.950001,30.559999,27.209999,29.340000,0,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,1062819,^VIX,None,1998-11-18,27.129999,28.459999,27.129999,28.129999,0,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,1062820,^VIX,None,1998-11-19,25.500000,26.400000,25.309999,26.100000,0,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,1062821,^VIX,None,1998-11-20,22.469999,24.010000,22.430000,24.010000,0,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,1062822,^VIX,None,1998-11-23,21.840000,22.230000,21.240000,22.200001,0,25.956,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False

#### S&P500の時系列データを取得

In [ ]:
sp500 = '^GSPC'
"""
response = request_api.update_stock_timeseries_data(
    code=sp500,
    market=None,
    start=start,
    end=end
)
response
"""

{'result': True}

In [10]:
sp_timeseries_df = request_api.get_stock_time_series_data(
    code=sp500,
    market=None,
    start=start,
    end=end
)
sp_timeseries_df.head()

取得件数: 6900

,id,stock_code,stock_market,date,open,high,low,close,volume,ma5,...,upper1,lower1,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,1069718,^GSPC,None,1998-11-17,1139.319946,1151.709961,1129.670044,1135.869995,705200000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,1069719,^GSPC,None,1998-11-18,1144.479980,1144.520020,1133.069946,1139.319946,652510000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,1069720,^GSPC,None,1998-11-19,1152.609985,1155.099976,1144.420044,1144.479980,671000000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,1069721,^GSPC,None,1998-11-20,1163.550049,1163.550049,1152.609985,1152.609985,721200000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,1069722,^GSPC,None,1998-11-23,1188.209961,1188.209961,1163.550049,1163.550049,774100000,1147.165991,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False

#### 銘柄リストの時系列データを取得

In [ ]:
# 銘柄リスト
miners = [
    # Undervalued Producers
    { "name": "Avino Silver & Gold Mines", "code": "ASM", "market": "TO" },
    { "name": "Americas Gold & Silver", "code": "USAS", "market": "" },
    { "name": "Santacruz Silver Mining", "code": "SCZ", "market": "V" },
    { "name": "Guanajuato Silver", "code": "GSVR", "market": "V" },
    { "name": "Aya Gold & Silver", "code": "AYA", "market": "TO" },
    { "name": "Andean Precious Metals", "code": "APM", "market": "TO" },

    # Near-Term Producers
    { "name": "Silverco Mining", "code": "SICO", "market": "V" },
    { "name": "Silver Mountain Resources", "code": "AGMR", "market": "V" },
    { "name": "Silver Storm Mining", "code": "SVRS", "market": "V" },
    { "name": "Andean Silver", "code": "ASL", "market": "AX" },

    # Developers
    { "name": "Discovery Silver", "code": "DSV", "market": "TO" },
    { "name": "GoGold Resources", "code": "GGD", "market": "TO" },
    { "name": "Vizsla Silver", "code": "VZLA", "market": "" },
    { "name": "Vizsla Silver (TSX)", "code": "VZLA", "market": "TO" },
    { "name": "Aftermath Silver", "code": "AAGFF", "market": "" },
    { "name": "Blackrock Silver", "code": "BKRRF", "market": "" },
    { "name": "Silver Tiger Metals", "code": "SLVR", "market": "V" },
    { "name": "Highlander Silver", "code": "HSLV", "market": "TO" },
    { "name": "Outcrop Silver & Gold", "code": "OCGSF", "market": "" },
    { "name": "Silver X Mining", "code": "AGX", "market": "V" },

    # Optionality
    { "name": "Chesapeake Gold", "code": "CHPGF", "market": "" },
    { "name": "Eloro Resources", "code": "ELO", "market": "TO" },
    { "name": "Hycroft Mining", "code": "HYMC", "market": "" },
    { "name": "Southern Silver Exploration", "code": "SSVFF", "market": "" }
]
"""
for miner in miners:
    # /api/v1/search/
    search_response = request_api.search_stock_data(
        miner["code"],
        miner["name"],
        miner["market"]
    )
    print(search_response['name'])
"""

AVINO SILVER AND GOLD MINES LTD
Americas Gold and Silver Corpor
SANTACRUZ SILVER MINING LTD
GUANAJUATO SILVER COMPANY LTD
AYA GOLD AND SILVER INC
ANDEAN PRECIOUS METALS CORP
SILVERCO MINING LTD
SILVER MOUNTAIN RESOURCES INC
SILVER STORM MINING LTD
ANDEAN FPO [ASL]
DISCOVERY SILVER CORP
GOGOLD RESOURCES INC
Vizsla Silver Corp.
VIZSLA SILVER CORP
Aftermath Silver Ltd.
Blackrock Silver Corp.
SILVER TIGER METALS INC
HIGHLANDER SILVER CORP
Outcrop Silver & Gold Corp.
SILVER X MINING CORP
Chesapeake Gold Corp.
ELORO RESOURCES LTD
Hycroft Mining Holding Corporat
Southern Silver Exploration Cor

In [12]:
search_response

{'found': True,
 'market': '',
 'name': 'Southern Silver Exploration Cor',
 'code': 'SSVFF'}

In [ ]:
# DBに銘柄を登録
"""
for miner in miners:
    # /api/v1/search/
    search_response = request_api.search_stock_data(
        miner["code"],
        miner["name"],
        miner["market"]
    )
    if search_response['found'] == True:
        # 銘柄を登録
        request_api.update_stock_timeseries_data(
            code=miner["code"],
            market=miner["market"],
            start=start,
            end=end
        )
        request_api.update_corp_finance_data(
            code=miner["code"],
            market=miner["market"]
        )
    else:
        results = {"name": None, "code": None}
"""

POST response: {'detail': 'market is required'}
POST response: {'detail': 'An unexpected error occurred'}
POST response: {'detail': 'market is required'}
POST response: {'detail': 'market is required'}
POST response: {'detail': 'market is required'}
POST response: {'detail': 'market is required'}
POST response: {'detail': 'market is required'}
POST response: {'detail': 'market is required'}
POST response: {'detail': 'market is required'}

In [14]:
def stock_prices_and_gold_prices(
        code: str,
        name: str,
        start: str,
        end: str,
        df_sp: pd.DataFrame | None = None,
        df_gold: pd.DataFrame | None = None,
        df_silver: pd.DataFrame | None = None
    ):
    # /api/v1/time_series_data/stock/
    response = request_api.get_stock_time_series_data(
        code=code,
        market=None,
        start=start,
        end=end
    )
    df_stock = pd.DataFrame(response)

    # S&P500を統合
    if df_sp is not None:
        df_sp_tmp = df_sp.copy() if df_sp is not None else pd.DataFrame()
        if "date" not in df_sp_tmp.columns:
            df_sp_tmp = df_sp_tmp.reset_index()

        df_sp_tmp["date"] = pd.to_datetime(df_sp_tmp["date"])
        df_sp_tmp = df_sp_tmp.set_index("date")
        df_sp_tmp = df_sp_tmp.loc[start:end]

    # 金価格を統合
    if df_gold is not None:
        df_gold_tmp = df_gold.copy() if df_gold is not None else pd.DataFrame()
        if "date" not in df_gold_tmp.columns:
            df_gold_tmp = df_gold_tmp.reset_index()
        df_gold_tmp["date"] = pd.to_datetime(df_gold_tmp["date"])
        df_gold_tmp = df_gold_tmp.set_index("date")
        df_gold_tmp = df_gold_tmp.loc[start:end]

    # 銀価格を統合
    if df_silver is not None:
        df_silver_tmp = df_silver.copy() if df_silver is not None else pd.DataFrame()
        if "date" not in df_silver_tmp.columns:
            df_silver_tmp = df_silver_tmp.reset_index()
        df_silver_tmp["date"] = pd.to_datetime(df_silver_tmp["date"])
        df_silver_tmp = df_silver_tmp.set_index("date")
        df_silver_tmp = df_silver_tmp.loc[start:end]

    # 金価格
    df = df_stock.copy()
    df["date"] = pd.to_datetime(df["date"])
    df = df.set_index("date")
    df = df.loc[start:end]


    # インデックスを揃えて結合
    if df_sp is not None:
        df["MA5_SP"] = df_sp_tmp["ma5"].reindex(df.index)
        df["MA25_SP"] = df_sp_tmp["ma25"].reindex(df.index)
    if df_gold is not None:
        df["MA5_GOLD"] = df_gold_tmp["ma5"].reindex(df.index)
        df["MA25_GOLD"] = df_gold_tmp["ma25"].reindex(df.index)
    if df_silver is not None:
        df["MA5_SILVER"] = df_silver_tmp["ma5"].reindex(df.index)
        df["MA25_SILVER"] = df_silver_tmp["ma25"].reindex(df.index)

    show_plot = ShowPlot()
    fig = show_plot.create_basic_chart(
        df=df.reset_index(),
        code=code,
        name=name,
        start=start,
        end=end
    )
    # ★ 2つのY軸を定義（左：HYMC、右：SP500 & GOLD）
    fig.update_layout(
        yaxis=dict(
            title=f"{name} Price",
            side="left"
        ),
        yaxis2=dict(
            title="SP500 / GOLD",
            overlaying="y",
            side="right"
        )
    )

    # --- SP500（右軸） ---
    if df_sp is not None:
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA5_SP"],
                name="SP_MA5",
                line={"color": "blue", "width": 1.2},
                yaxis="y2"   # ★ 右軸
            )
        )
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA25_SP"],
                name="SP_MA25",
                line={"color": "gray", "width": 1.2},
                yaxis="y2"   # ★ 右軸
            )
        )

    # --- GOLD（右軸） ---
    if df_gold is not None:
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA5_GOLD"],
                name="GOLD_MA5",
                line={"color": "orange", "width": 1.2},
                yaxis="y2"   # ★ 右軸
            )
        )
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA25_GOLD"],
                name="GOLD_MA25",
                line={"color": "yellow", "width": 1.2},
                yaxis="y2"   # ★ 右軸
            )
        )

    # --- SILVER（左軸） ---
    if df_silver is not None:
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA5_SILVER"],
                name="SILVER_MA5",
                line={"color": "gray", "width": 1.2},
                yaxis="y"   # ★ 左軸
            )
        )
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA25_SILVER"],
                name="SILVER_MA25",
                line={"color": "black", "width": 1.2},
                yaxis="y"   # ★ 左軸
            )
        )

    return fig

In [15]:
code = "HYMC"
name = "Hycroft Mining"
start = dt.datetime(2025, 1, 1).strftime("%Y-%m-%d")
end = dt.datetime(2026, 4, 17).strftime("%Y-%m-%d")
# グラフ領域の作成
fig = stock_prices_and_gold_prices(
    code=code,
    name=name,
    start=start,
    end=end,
    df_sp=None,
    df_gold=gold_df,
    df_silver=silver_df
)
fig.show()

取得件数: 530

In [16]:
response = request_api.update_corp_finance_data(
    code=code,
    market=None
)
response

POST response: {'detail': 'market is required'}

{}

In [17]:
hymc_financials_data = request_api.get_corp_financials_data(code=code, market=None)
hymc_balance_sheet_data = request_api.get_corp_balance_sheet_data(code=code, market=None)
hymc_cash_flow_data = request_api.get_corp_cash_flow_data(code=code, market=None)
hymc_earnings_data = request_api.get_corp_earnings_data(code=code, market=None)
hymc_quarterly_earnings_data = request_api.get_corp_quarterly_earnings_data(code=code, market=None)

GET response: {'detail': [{'type': 'missing', 'loc': ['query', 'market'], 'msg': 'Field required', 'input': None}]}
GET response: {'detail': [{'type': 'missing', 'loc': ['query', 'market'], 'msg': 'Field required', 'input': None}]}
GET response: {'detail': [{'type': 'missing', 'loc': ['query', 'market'], 'msg': 'Field required', 'input': None}]}
GET response: {'detail': [{'type': 'missing', 'loc': ['query', 'market'], 'msg': 'Field required', 'input': None}]}
GET response: {'detail': [{'type': 'missing', 'loc': ['query', 'market'], 'msg': 'Field required', 'input': None}]}

In [18]:
print(hymc_financials_data)

{}