In [4]:
import os
import sys
import requests
import datetime as dt
from dotenv import load_dotenv
from pathlib import Path
import requests
import pandas as pd
import talib as ta
import plotly.graph_objs as go

import ipywidgets as widgets
from ipywidgets import Dropdown, Text, Button, Output
from IPython.display import display

from Modules.rci import Rci

In [5]:
# APIの接続先（notebookコンテナでは通常 http://api:8000 が設定される）
API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")
# データを取得する関数
sys.path.append("/workspace/notebook")

In [16]:
# S&P 500の時系列データを登録
code = "SPY"
market = ""
start = dt.datetime(1999, 1, 1).strftime("%Y-%m-%d")
end = dt.datetime.now().strftime("%Y-%m-%d")
"""
post_payload = {
    "code": code,
    "market": market,
    "start": start,
    "end": end
}

# /api/v1/stock_price/
post_url = f"{API_BASE_URL}/api/v1/stock_price/"
post_response = requests.post(post_url, json=post_payload, timeout=60)

print("POST URL:", post_url)
print("POST status:", post_response.status_code)
print("POST response:", post_response.json())
"""

'\npost_payload = {\n    "code": code,\n    "market": market,\n    "start": start,\n    "end": end\n}\n\n# /api/v1/stock_price/\npost_url = f"{API_BASE_URL}/api/v1/stock_price/"\npost_response = requests.post(post_url, json=post_payload, timeout=60)\n\nprint("POST URL:", post_url)\nprint("POST status:", post_response.status_code)\nprint("POST response:", post_response.json())\n'

### S&P500の時系列データを取得

In [ ]:
get_url = f"{API_BASE_URL}/api/v1/time_series_data/stock/"
get_params = {
    "code": code,
    "market": market,
    "start": start,
    "end": end
}

get_response = requests.get(get_url, params=get_params, timeout=60)

print("GET URL:", get_url)
print("GET status:", get_response.status_code)

if get_response.status_code == 200:
    get_json = get_response.json()
    results = get_json.get("results", [])
    df_sp = pd.DataFrame(results)

    print("取得件数:", len(df_sp))
    display(df_sp)
else:
    print("GET response:", get_response.json())

GET URL: http://api:8000/api/v1/time_series_data/stock/
GET status: 200
取得件数: 6895

,id,stock_code,stock_market,date,open,high,low,close,volume,ma5,...,upper1,lower1,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,1118373,SPY,,1998-11-17,70.659531,71.627469,70.001332,70.407867,9058900,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,1118374,SPY,,1998-11-18,71.085411,71.240281,70.311060,70.814388,4567700,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,1118375,SPY,,1998-11-19,71.704849,71.801643,71.007934,71.414468,5249300,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,1118376,SPY,,1998-11-20,72.246925,72.324360,71.762956,72.082376,5562000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,1118377,SPY,,1998-11-23,73.950516,74.105386,72.576043,72.769631,7151300,71.497746,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6890,1125263,SPY,,2026-04-13,686.099976,686.299988,676.580017,677.409973,54185800,673.322009,...,673.374924,649.246814,True,NaN,NaN,NaN,NaN,NaN,NaN,False
6891,1125264,SPY,,2026-04-14,694.460022,694.580017,687.659973,687.690002,63480500,679.530005,...,675.353952,649.116979,True,NaN,NaN,NaN,NaN,NaN,NaN,False
6892,1125265,SPY,,2026-04-15,699.940002,700.280029,694.200012,695.260010,58240400,683.304004,...,677.421927,648.599874,True,NaN,NaN,NaN,NaN,NaN,NaN,False
6893,1125266,SPY,,2026-04-16,701.659973,702.780029,698.530029,701.059998,49972400,688.547998,...,680.088946,647.958889,True,NaN,NaN,NaN,NaN,NaN,NaN,False
6894,1125267,SPY,,2026-04-17,710.140015,712.390015,705.760010,706.140015,70538900,693.512000,...,683.544535,647.447941,True,NaN,NaN,NaN,NaN,NaN,NaN,False

### 金価格のデータを登録

In [19]:
# 金の時系列データを登録
code = "GC=F"
start = dt.datetime(1999, 1, 1).strftime("%Y-%m-%d")
end = dt.datetime.now().strftime("%Y-%m-%d")
"""
post_payload = {
    "code": code,
    "market": None,
    "start": "1999-01-01",
    "end": "2026-04-18"
}

# /api/v1/commodity_data/
post_url = f"{API_BASE_URL}/api/v1/commodity_data/"
post_response = requests.post(post_url, json=post_payload, timeout=60)

print("POST URL:", post_url)
print("POST status:", post_response.status_code)
print("POST response:", post_response.json())
"""

'\npost_payload = {\n    "code": code,\n    "market": None,\n    "start": "1999-01-01",\n    "end": "2026-04-18"\n}\n\n# /api/v1/commodity_data/\npost_url = f"{API_BASE_URL}/api/v1/commodity_data/"\npost_response = requests.post(post_url, json=post_payload, timeout=60)\n\nprint("POST URL:", post_url)\nprint("POST status:", post_response.status_code)\nprint("POST response:", post_response.json())\n'

###

In [ ]:
# /api/v1/time_series_data/commodity/
get_url = f"{API_BASE_URL}/api/v1/time_series_data/commodity/"
get_params = {
    "code": code,
    "market": None,
    "start": start,
    "end": end
}

get_response = requests.get(get_url, params=get_params, timeout=60)

print("GET URL:", get_url)
print("GET status:", get_response.status_code)

if get_response.status_code == 200:
    get_json = get_response.json()
    results = get_json.get("results", [])
    df_gold = pd.DataFrame(results)

    print("取得件数:", len(df_gold))
    display(df_gold)
else:
    print("GET response:", get_response.json())

GET URL: http://api:8000/api/v1/time_series_data/commodity/
GET status: 200
取得件数: 6431

,id,commodity_id,commodity_code,commodity_market,date,open,high,low,close,adj_close,...,rci9,rci26,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,9,14,GC=F,None,2000-08-30,273.899994,273.899994,273.899994,273.899994,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,10,14,GC=F,None,2000-08-31,278.299988,278.299988,274.799988,274.799988,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,11,14,GC=F,None,2000-09-01,277.000000,277.000000,277.000000,277.000000,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,12,14,GC=F,None,2000-09-05,275.799988,275.799988,275.799988,275.799988,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,13,14,GC=F,None,2000-09-06,274.200012,274.200012,274.200012,274.200012,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6426,6435,14,GC=F,None,2026-04-13,4742.399902,4742.399902,4704.000000,4704.000000,None,...,40.000000,-59.726496,False,NaN,NaN,NaN,NaN,NaN,NaN,False
6427,6436,14,GC=F,None,2026-04-14,4825.000000,4841.600098,4770.100098,4770.100098,None,...,40.000000,-51.111111,False,NaN,NaN,NaN,NaN,NaN,NaN,False
6428,6437,14,GC=F,None,2026-04-15,4800.000000,4843.600098,4798.000000,4843.600098,None,...,48.333333,-39.555556,True,4754.92002,NaN,NaN,NaN,NaN,NaN,False
6429,6438,14,GC=F,None,2026-04-16,4785.399902,4810.899902,4785.399902,4810.899902,None,...,81.666667,-28.000000,True,NaN,NaN,NaN,NaN,NaN,NaN,False
6430,6439,14,GC=F,None,2026-04-17,4857.600098,4879.700195,4767.200195,4771.600098,None,...,78.333333,-15.213675,True,NaN,NaN,NaN,NaN,NaN,NaN,False