In [1]:
import os
import sys
import requests
import datetime as dt
import numpy as np
from dotenv import load_dotenv
from pathlib import Path
import requests
import pandas as pd
import talib as ta
import plotly.graph_objs as go

import ipywidgets as widgets
from ipywidgets import Dropdown, Text, Button, Output
from IPython.display import display

from Modules.utility import Utility
from Modules.show_plot import ShowPlot
from Modules.reques_api import RequestApi
from Modules.get_market_data import GetMarketData
from Modules.stock_prices_and_market_data import ClassStockPricesMarketData
from Modules.financial import Financial
from Modules.pdf_url_to_markdown import PDFUrlToMarkdown
from Modules.webpage_to_markdown import WebpageToMarkdown

In [2]:
API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")
request_api = RequestApi(API_BASE_URL)
get_market_data = GetMarketData(Path('/workspace/data'))
utility = Utility()
stock_prices_market_data = ClassStockPricesMarketData()
financial = Financial()
# URLからPDFをダウンロードしてMarkdownに変換するクラスのインスタンスを作成
pdf_to_md = PDFUrlToMarkdown()
# WEBページをMarkdownに変換する関数
webpage_to_markdown = WebpageToMarkdown()

### 金価格の時系列データを取得

In [3]:
gold = 'GC=F'
start = '1999-01-01'
end = dt.datetime.now().strftime('%Y-%m-%d')
response = request_api.update_commodity_timeseries_data(
    code='GC=F',
    market=None,
    start=start,
    end=end
)
response

{'result': True}

In [4]:
gold_df = request_api.get_commodity_time_series_data(
    code=gold,
    market=None,
    start=start,
    end=end
)
gold_df.head()

取得件数: 6449

,id,commodity_id,commodity_code,commodity_market,date,open,high,low,close,adj_close,...,rci9,rci26,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,1,1,GC=F,None,2000-08-30,273.899994,273.899994,273.899994,273.899994,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,2,1,GC=F,None,2000-08-31,278.299988,278.299988,274.799988,274.799988,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,3,1,GC=F,None,2000-09-01,277.000000,277.000000,277.000000,277.000000,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,4,1,GC=F,None,2000-09-05,275.799988,275.799988,275.799988,275.799988,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,5,1,GC=F,None,2000-09-06,274.200012,274.200012,274.200012,274.200012,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False

### 銀価格の時系列データを取得

In [5]:
silver = 'GC=F'
start = '1999-01-01'
end = dt.datetime.now().strftime('%Y-%m-%d')
response = request_api.update_commodity_timeseries_data(
    code='GC=F',
    market=None,
    start=start,
    end=end
)
response

{'result': True}

In [6]:
silver_df = request_api.get_commodity_time_series_data(
    code=silver,
    market=None,
    start=start,
    end=end
)
silver_df.head()

取得件数: 6449

,id,commodity_id,commodity_code,commodity_market,date,open,high,low,close,adj_close,...,rci9,rci26,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,1,1,GC=F,None,2000-08-30,273.899994,273.899994,273.899994,273.899994,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,2,1,GC=F,None,2000-08-31,278.299988,278.299988,274.799988,274.799988,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,3,1,GC=F,None,2000-09-01,277.000000,277.000000,277.000000,277.000000,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,4,1,GC=F,None,2000-09-05,275.799988,275.799988,275.799988,275.799988,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,5,1,GC=F,None,2000-09-06,274.200012,274.200012,274.200012,274.200012,None,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False

#### S&P500の時系列データを取得

In [7]:
sp500 = '^GSPC'

response = request_api.update_stock_timeseries_data(
    code=sp500,
    market=None,
    start=start,
    end=end
)
response

{'result': True}

In [8]:
sp_timeseries_df = request_api.get_stock_time_series_data(
    code=sp500,
    market=None,
    start=start,
    end=end
)
sp_timeseries_df.head()

取得件数: 6913

,id,stock_code,stock_market,date,open,high,low,close,volume,ma5,...,upper1,lower1,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,1069718,^GSPC,None,1998-11-17,1139.319946,1151.709961,1129.670044,1135.869995,705200000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,1069719,^GSPC,None,1998-11-18,1144.479980,1144.520020,1133.069946,1139.319946,652510000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,1069720,^GSPC,None,1998-11-19,1152.609985,1155.099976,1144.420044,1144.479980,671000000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,1069721,^GSPC,None,1998-11-20,1163.550049,1163.550049,1152.609985,1152.609985,721200000,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
4,1069722,^GSPC,None,1998-11-23,1188.209961,1188.209961,1163.550049,1163.550049,774100000,1147.165991,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False

#### USASの時系列データを取得

In [9]:
usas = 'USAS'

response = request_api.update_stock_timeseries_data(
    code=usas,
    market=None,
    start=start,
    end=end
)
response

{'result': True}

In [10]:
usas_timeseries_df = request_api.get_stock_time_series_data(
    code=usas,
    market=None,
    start=start,
    end=end
)
usas_timeseries_df

取得件数: 11331

,id,stock_code,stock_market,date,open,high,low,close,volume,ma5,...,upper1,lower1,cross,gc,dc,macd_gc,macd_dc,rci_gc,rci_dc,rising_condition
0,1083510,USAS,,2003-10-27,20.10,20.1000,20.1000,20.10,50,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
1,1155668,USAS,NaN,2003-10-27,20.10,20.1000,20.1000,20.10,50,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
2,1083511,USAS,,2003-10-28,20.10,20.1000,20.1000,20.10,0,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
3,1155669,USAS,NaN,2003-10-28,20.10,20.1000,20.1000,20.10,0,NaN,...,NaN,NaN,False,NaN,NaN,NaN,-0.090566,NaN,NaN,False
4,1083512,USAS,,2003-10-29,20.10,20.1000,20.1000,20.10,0,20.100,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11326,1210261,USAS,NaN,2026-05-07,6.38,7.0400,6.3300,6.77,6203300,6.034,...,6.469313,5.806688,False,NaN,NaN,0.017207,NaN,NaN,NaN,False
11327,1210262,USAS,NaN,2026-05-08,6.63,6.7300,6.3000,6.58,4163800,6.212,...,6.501985,5.819615,True,6.212,NaN,NaN,NaN,NaN,NaN,False
11328,1210263,USAS,NaN,2026-05-11,7.14,7.2200,6.8000,6.92,7096200,6.450,...,6.567643,5.826757,True,NaN,NaN,NaN,NaN,NaN,NaN,False
11329,1210264,USAS,NaN,2026-05-12,7.41,7.4800,6.7200,6.93,6138600,6.628,...,6.624078,5.829522,True,NaN,NaN,NaN,NaN,NaN,NaN,False
11330,1210265,USAS,NaN,2026-05-13,7.25,7.5099,7.0201,7.32,5179576,6.904,...,6.723150,5.820850,True,NaN,NaN,NaN,NaN,NaN,NaN,False

#### チャート

In [11]:
def stock_prices_and_gold_prices(
        code: str,
        name: str,
        start: str,
        end: str,
        df_sp: pd.DataFrame | None = None,
        df_gold: pd.DataFrame | None = None,
        df_silver: pd.DataFrame | None = None
    ):
    # /api/v1/time_series_data/stock/
    response = request_api.get_stock_time_series_data(
        code=code,
        market=None,
        start=start,
        end=end
    )
    df_stock = pd.DataFrame(response)

    # S&P500を統合
    if df_sp is not None:
        df_sp_tmp = df_sp.copy() if df_sp is not None else pd.DataFrame()
        if "date" not in df_sp_tmp.columns:
            df_sp_tmp = df_sp_tmp.reset_index()

        df_sp_tmp["date"] = pd.to_datetime(df_sp_tmp["date"])
        df_sp_tmp = df_sp_tmp.set_index("date")
        df_sp_tmp = df_sp_tmp.loc[start:end]

    # 金価格を統合
    if df_gold is not None:
        df_gold_tmp = df_gold.copy() if df_gold is not None else pd.DataFrame()
        if "date" not in df_gold_tmp.columns:
            df_gold_tmp = df_gold_tmp.reset_index()
        df_gold_tmp["date"] = pd.to_datetime(df_gold_tmp["date"])
        df_gold_tmp = df_gold_tmp.set_index("date")
        df_gold_tmp = df_gold_tmp.loc[start:end]

    # 銀価格を統合
    if df_silver is not None:
        df_silver_tmp = df_silver.copy() if df_silver is not None else pd.DataFrame()
        if "date" not in df_silver_tmp.columns:
            df_silver_tmp = df_silver_tmp.reset_index()
        df_silver_tmp["date"] = pd.to_datetime(df_silver_tmp["date"])
        df_silver_tmp = df_silver_tmp.set_index("date")
        df_silver_tmp = df_silver_tmp.loc[start:end]

    # 金価格
    df = df_stock.copy()
    df["date"] = pd.to_datetime(df["date"])
    df = df.set_index("date")
    df = df.loc[start:end]


    # インデックスを揃えて結合
    if df_sp is not None:
        df["MA5_SP"] = df_sp_tmp["ma5"].reindex(df.index)
        df["MA25_SP"] = df_sp_tmp["ma25"].reindex(df.index)
    if df_gold is not None:
        df["MA5_GOLD"] = df_gold_tmp["ma5"].reindex(df.index)
        df["MA25_GOLD"] = df_gold_tmp["ma25"].reindex(df.index)
    if df_silver is not None:
        df["MA5_SILVER"] = df_silver_tmp["ma5"].reindex(df.index)
        df["MA25_SILVER"] = df_silver_tmp["ma25"].reindex(df.index)

    show_plot = ShowPlot()
    fig = show_plot.create_basic_chart(
        df=df.reset_index(),
        code=code,
        name=name,
        start=start,
        end=end
    )
    # ★ 2つのY軸を定義（左：HYMC、右：SP500 & GOLD）
    fig.update_layout(
        yaxis=dict(
            title=f"{name} Price",
            side="left"
        ),
        yaxis2=dict(
            title="SP500 / GOLD",
            overlaying="y",
            side="right"
        )
    )

    # --- SP500（右軸） ---
    if df_sp is not None:
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA5_SP"],
                name="SP_MA5",
                line={"color": "blue", "width": 1.2},
                yaxis="y2"   # ★ 右軸
            )
        )
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA25_SP"],
                name="SP_MA25",
                line={"color": "gray", "width": 1.2},
                yaxis="y2"   # ★ 右軸
            )
        )

    # --- GOLD（右軸） ---
    if df_gold is not None:
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA5_GOLD"],
                name="GOLD_MA5",
                line={"color": "orange", "width": 1.2},
                yaxis="y2"   # ★ 右軸
            )
        )
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA25_GOLD"],
                name="GOLD_MA25",
                line={"color": "yellow", "width": 1.2},
                yaxis="y2"   # ★ 右軸
            )
        )

    # --- SILVER（左軸） ---
    if df_silver is not None:
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA5_SILVER"],
                name="SILVER_MA5",
                line={"color": "gray", "width": 1.2},
                yaxis="y"   # ★ 左軸
            )
        )
        fig.add_trace(
            go.Scatter(
                x=df.index,
                y=df["MA25_SILVER"],
                name="SILVER_MA25",
                line={"color": "black", "width": 1.2},
                yaxis="y"   # ★ 左軸
            )
        )

    return fig

#### 金銀価格を含むチャート

In [12]:
name = "Americas Gold and Silver"
start = dt.datetime(2025, 1, 1).strftime("%Y-%m-%d")
end = dt.datetime(2026, 4, 17).strftime("%Y-%m-%d")
# グラフ領域の作成
fig = stock_prices_and_gold_prices(
    code=usas,
    name=name,
    start=start,
    end=end,
    df_sp=None,
    df_gold=gold_df,
    df_silver=silver_df
)
fig.show()

取得件数: 1060

#### 株価のみのチャート

In [13]:
name = "Americas Gold and Silver"
start = dt.datetime(2025, 1, 1).strftime("%Y-%m-%d")
end = dt.datetime(2026, 4, 17).strftime("%Y-%m-%d")
# グラフ領域の作成
fig = stock_prices_and_gold_prices(
    code=usas,
    name=name,
    start=start,
    end=end,
    df_sp=None,
    df_gold=None,
    df_silver=None
)
fig.show()

取得件数: 1060

#### 財務データ

In [14]:
response = request_api.update_corp_finance_data(
    code=usas,
    market=None
)
response

{'result': True}

In [15]:
usas_financials_data = request_api.get_corp_financials_data(code=usas, market=None)
usas_balance_sheet_data = request_api.get_corp_balance_sheet_data(code=usas, market=None)
usas_cash_flow_data = request_api.get_corp_cash_flow_data(code=usas, market=None)
usas_earnings_data = request_api.get_corp_earnings_data(code=usas, market=None)
usas_quarterly_earnings_data = request_api.get_corp_quarterly_earnings_data(code=usas, market=None)

In [16]:
# ４年分の財務データ
usas_financials_data_df = pd.DataFrame(usas_financials_data['results'])
# ４年分のバランスシート
usas_balance_sheet_data_df = pd.DataFrame(usas_balance_sheet_data['results'])
# ４年分のキャッシュフロー
usas_cash_flow_data_df = pd.DataFrame(usas_cash_flow_data['results'])
# ４年分の収益データ
usas_earnings_data_df = pd.DataFrame(usas_earnings_data['results'])
# ４年分の四半期収益データ
usas_quarterly_earnings_data_df = pd.DataFrame(usas_quarterly_earnings_data['results'])

In [17]:
"""
◆ 1. 株価・市場データ
• 現在株価（Price）
• 時価総額（Market Cap）
• 出来高（Volume）
• 52週高値・安値
• Beta（ボラティリティ指標）ß
"""
stock_prices_market_data.stock_prices_and_market_data(
    code=usas,
    market=None,
    bs_df=usas_balance_sheet_data_df
)

取得件数: 922
取得件数: 461
取得件数: 920
取得件数: 460
取得件数: 916
取得件数: 458
取得件数: 918
取得件数: 459
取得件数: 916
取得件数: 458

,close,market_cap,shares_outstanding,higher_rate_par_52_weeks,lower_rate_par_52_weeks,beta
0,6.025,NaN,NaN,9.750,1.700,0.677226
1,5.850,1.196066e+09,204455721.0,6.800,0.925,0.382291
2,3.125,6.834055e+08,218689766.0,3.275,0.525,0.395748
3,1.225,7.282016e+08,594450243.0,1.500,0.500,0.485434
4,0.625,2.002617e+08,320418782.0,6.240,0.500,0.683736

In [18]:
"""
◆ 2. 財務データ（Financials）+ EPS（Earnings Per Share）+ PBR（Price-to-Book Ratio）
• 売上高（Revenue）
• 営業利益（Operating Income）
• 純利益（Net Income）
• EBITDA（企業による）
• 総資産（Total Assets）
• 総負債（Total Liabilities）
• 現金（Cash）
• 希釈EPS（Diluted EPS）
• 基本EPS（Basic EPS）
• 営業キャッシュフロー（Operating Cash Flow）
• フリーキャッシュフロー（Free Cash Flow）
"""
financial_df = financial.calc_financial(
    code = usas,
    market = None,
)
financial_df.to_markdown()

取得件数: 2042

'|    | date                |       revenue |     earnings |   total_assets |   total_debt |   cash_and_cash_equivalents |      EBITDA |   operating_income |   basic_eps |   diluted_eps |   operating_cash_flow |   free_cash_flow |\n|---:|:--------------------|--------------:|-------------:|---------------:|-------------:|----------------------------:|------------:|-------------------:|------------:|--------------:|----------------------:|-----------------:|\n|  0 | 2021-12-31 00:00:00 | nan           | nan          |  nan           | nan          |               nan           |  0          |       nan          |  nan        |    nan        |           nan         |     nan          |\n|  1 | 2022-12-31 00:00:00 |   8.5016e+07  |  -4.3104e+07 |    1.90819e+08 |   1.2343e+07 |                 1.964e+06   | -1.8331e+07 |        -2.6507e+07 |   -0.575    |     -0.23     |            -1.179e+06 |      -2.0781e+07 |\n|  2 | 2023-12-31 00:00:00 |   9.516e+07   |  -3.4958e+07 |    1.80488e+08 |   2.1909e+07 |                 2.061e+06   | -1.1195e+07 |        -2.2814e+07 |   -0.4      |     -0.16     |            -1.013e+06 |      -2.0954e+07 |\n|  3 | 2024-12-31 00:00:00 |   1.00188e+08 |  -4.5065e+07 |    1.9264e+08  |   2.2339e+07 |                 2.0002e+07  | -1.6859e+07 |        -2.6242e+07 |   -0.425    |     -0.425    |            -3.068e+06 |      -2.1918e+07 |\n|  4 | 2025-12-31 00:00:00 |   1.17934e+08 |  -8.7446e+07 |    4.12996e+08 |   5.567e+07  |                 1.29783e+08 | -5.6268e+07 |        -2.5913e+07 |   -0.272768 |     -0.272768 |            -3.945e+06 |      -7.3185e+07 |'

In [19]:
# PBR（Price-to-Book Ratio）やROE（Return on Equity）などの投資指標を計算
financial.calc_stock_investment_indicators(code=usas, market=None).to_markdown()

取得件数: 901

'|    | date                |   EV | reason   |        BPS |       PBR |        ROE |   operating_income |   basic_eps |   diluted_eps |\n|---:|:--------------------|-----:|:---------|-----------:|----------:|-----------:|-------------------:|------------:|--------------:|\n|  0 | 2021-12-31 00:00:00 |  nan | no_price | nan        | nan       | nan        |       nan          |  nan        |    nan        |\n|  1 | 2022-12-31 00:00:00 |  nan | no_price | nan        | nan       |  -0.530661 |        -2.6507e+07 |   -0.575    |     -0.23     |\n|  2 | 2023-12-31 00:00:00 |  nan | no_price | nan        | nan       |  -0.654424 |        -2.2814e+07 |   -0.4      |     -0.16     |\n|  3 | 2024-12-31 00:00:00 |  nan | nan      |   0.10453  |   8.84912 |  -0.725241 |        -2.6242e+07 |   -0.425    |     -0.425    |\n|  4 | 2025-12-31 00:00:00 |  nan | nan      |   0.691648 |   7.54719 |  -0.394582 |        -2.5913e+07 |   -0.272768 |     -0.272768 |'

◆ 3. P/NAV（NAVはYahooでは取得不可）
Yahoo Finance では NAV は取得できないため、
企業の NI 43‑101 技術報告書（Technical Report） から取得する必要があります。
[ P/NAV = \frac{時価総額}{NAV}
 ]


◆ 4. AISC（All-in Sustaining Cost）
AISC は Yahoo Finance では取得不可。
企業の四半期報告書（MD&A） に記載されています。


◆ 5. 資源量（Reserves/Resources）
Yahoo Finance では取得不可。
NI 43‑101 技術報告書 または 企業プレゼン資料 から取得。

### 決算資料を取得

In [21]:
#md_file_path =pdf_to_md.pdf_url_to_markdown(
#    pdf_url="",
#    directory_path="/workspace/data",
#)
#md_file_path

In [22]:

md_file_path = md_file_path =pdf_to_md.pdf_url_to_markdown(
    pdf_url = 'https://americas-gold.com/site/assets/files/6086/2025q4fsv2.pdf',
    directory_path = '/workspace/data'
)
md_file_path

Generated: /workspace/data/2025q4fsv2.pdf.md

'/workspace/data/2025q4fsv2.pdf.md'

In [23]:

md_file_path = md_file_path =pdf_to_md.pdf_url_to_markdown(
    pdf_url = 'https://americas-gold.com/site/assets/files/6086/2025q4mda.pdf',
    directory_path = '/workspace/data'
)
md_file_path

Generated: /workspace/data/2025q4mda.pdf.md

'/workspace/data/2025q4mda.pdf.md'

In [24]:
md_file_path = md_file_path =pdf_to_md.pdf_url_to_markdown(
    pdf_url = 'https://americas-gold.com/site/assets/files/6070/ags_presentation_-_april_2026_slideshow_1.pdf',
    directory_path = '/workspace/data'
)
md_file_path

Generated: /workspace/data/ags_presentation_-_april_2026_slideshow_1.pdf.md

'/workspace/data/ags_presentation_-_april_2026_slideshow_1.pdf.md'

In [ ]:
md_file_path = md_file_path =pdf_to_md.pdf_url_to_markdown(
    pdf_url = '',
    directory_path = '/workspace/data'
)
md_file_path

markitdown failed (rc=-9). Falling back to pdftotext if available. stderr:
onnxruntime cpuid_info warning: Unknown CPU vendor. cpuinfo_vendor value: 0
Generated (pdftotext fallback): /workspace/data/Crawford-NI-43-101-FINAL-REPORT_Nov24_R2.pdf.md

'/workspace/data/Crawford-NI-43-101-FINAL-REPORT_Nov24_R2.pdf.md'

#### P/NAV

#### AISC（All-in Sustaining Cost）

#### 資源量（Reserves/Resources）